pipeline {
    agent any

    environment {
        IMAGE_NAME = "theangel11/flask-devops"
        IMAGE_TAG = "${env.BUILD_NUMBER}"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                script {
                    docker.build("${IMAGE_NAME}:${IMAGE_TAG}", "app")
                }
            }
        }

        stage('Test') {
            steps {
                echo 'Running unit tests...'
                script {
                    docker.image("${IMAGE_NAME}:${IMAGE_TAG}").inside {
                        sh 'python -m unittest discover src/tests'
                    }
                }
            }
        }

        stage('Package') {
            steps {
                withDockerRegistry([credentialsId: 'dockerhub-creds', url: '']) {
                    script {
                        docker.image("${IMAGE_NAME}:${IMAGE_TAG}").push()
                    }
                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                    sh """
                    kubectl set image deployment/flask-deployment flask=${IMAGE_NAME}:${IMAGE_TAG} --record
                    kubectl rollout status deployment/flask-deployment
                    """
                }
            }
        }
    }



}